### ISSUE TITLE
Sanity tests failing in infinidat.infinibox

### ISSUE THREAD

**Issue by dmsimard** [Infinidat/ansible-infinidat-collection#15]
##### SUMMARY
We are running sanity tests across every collection included in the Ansible community package (as part of [this issue](https://github.com/ansible-community/community-topics/issues/96)) and found that ``ansible-test sanity --docker`` against infinidat.infinibox 1.3.3 fails with ansible-core 2.13.0rc1 in ansible 6.0.0a2.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
n/a

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.0rc1]
```

##### COLLECTION VERSION

```paste below
1.3.3
```

##### STEPS TO REPRODUCE

```yaml
ansible-test sanity --docker
```

##### EXPECTED RESULTS

Tests are either passing or ignored.

##### ACTUAL RESULTS

```paste below
ERROR: Command "ansible-doc -t module infinidat.infinibox.infini_cluster infinidat.infinibox.infini_export infinidat.infinibox.infini_export_client infinidat.infinibox.infini_fs infinidat.infinibox.infini_host infinidat.infinibox.infini_map infinidat.infinibox.infini_pool infinidat.infinibox.infini_port infinidat.infinibox.infini_user infinidat.infinibox.infini_vol" returned exit status 1.
>>> Standard Error
ERROR! module infinidat.infinibox.infini_vol missing documentation (or could not parse documentation): while parsing a block collection
  in "<unicode string>", line 54, column 7
did not find expected '-' indicator
  in "<unicode string>", line 55, column 7[0m
ERROR: Found 1 future-import-boilerplate issue(s) which need to be resolved:
ERROR: plugins/module_utils/infinibox.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
ERROR: Found 11 import issue(s) on python 2.7 which need to be resolved:
ERROR: plugins/module_utils/infinibox.py:42:0: traceback: ImportError: No module named infinisdk.core.exceptions
ERROR: plugins/modules/infini_cluster.py:65:0: traceback: NameError: name 'api_wrapper' is not defined
ERROR: plugins/modules/infini_export.py:110:0: traceback: ImportError: No module named infinisdk.core.exceptions (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_export_client.py:97:0: traceback: ImportError: No module named infinisdk.core.exceptions (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_fs.py:73:0: traceback: ImportError: No module named infinisdk.core.exceptions (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_host.py:8:0: traceback: ImportError: No module named infi.dtypes.iqn
ERROR: plugins/modules/infini_map.py:90:0: traceback: ImportError: No module named infinisdk.core.exceptions
ERROR: plugins/modules/infini_pool.py:108:0: traceback: ImportError: No module named infinisdk.core.exceptions (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_port.py:68:0: traceback: ImportError: No module named infinisdk.core.exceptions (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_user.py:8:0: traceback: ImportError: No module named infi.dtypes.iqn
ERROR: plugins/modules/infini_vol.py:128:0: traceback: ImportError: No module named arrow
ERROR: Found 11 import issue(s) on python 3.5 which need to be resolved:
ERROR: plugins/module_utils/infinibox.py:42:0: traceback: ImportError: No module named 'infinisdk'
ERROR: plugins/modules/infini_cluster.py:65:0: traceback: NameError: name 'api_wrapper' is not defined
ERROR: plugins/modules/infini_export.py:110:0: traceback: ImportError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_export_client.py:97:0: traceback: ImportError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_fs.py:73:0: traceback: ImportError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_host.py:8:0: traceback: ImportError: No module named 'infi'
ERROR: plugins/modules/infini_map.py:90:0: traceback: ImportError: No module named 'infinisdk'
ERROR: plugins/modules/infini_pool.py:108:0: traceback: ImportError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_port.py:68:0: traceback: ImportError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_user.py:8:0: traceback: ImportError: No module named 'infi'
ERROR: plugins/modules/infini_vol.py:128:0: traceback: ImportError: No module named 'arrow'
ERROR: Found 11 import issue(s) on python 3.6 which need to be resolved:
ERROR: plugins/module_utils/infinibox.py:42:0: traceback: ModuleNotFoundError: No module named 'infinisdk'
ERROR: plugins/modules/infini_cluster.py:65:0: traceback: NameError: name 'api_wrapper' is not defined
ERROR: plugins/modules/infini_export.py:110:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_export_client.py:97:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_fs.py:73:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_host.py:8:0: traceback: ModuleNotFoundError: No module named 'infi'
ERROR: plugins/modules/infini_map.py:90:0: traceback: ModuleNotFoundError: No module named 'infinisdk'
ERROR: plugins/modules/infini_pool.py:108:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_port.py:68:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_user.py:8:0: traceback: ModuleNotFoundError: No module named 'infi'
ERROR: plugins/modules/infini_vol.py:128:0: traceback: ModuleNotFoundError: No module named 'arrow'
ERROR: Found 11 import issue(s) on python 3.7 which need to be resolved:
ERROR: plugins/module_utils/infinibox.py:42:0: traceback: ModuleNotFoundError: No module named 'infinisdk'
ERROR: plugins/modules/infini_cluster.py:65:0: traceback: NameError: name 'api_wrapper' is not defined
ERROR: plugins/modules/infini_export.py:110:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_export_client.py:97:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_fs.py:73:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_host.py:8:0: traceback: ModuleNotFoundError: No module named 'infi'
ERROR: plugins/modules/infini_map.py:90:0: traceback: ModuleNotFoundError: No module named 'infinisdk'
ERROR: plugins/modules/infini_pool.py:108:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_port.py:68:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_user.py:8:0: traceback: ModuleNotFoundError: No module named 'infi'
ERROR: plugins/modules/infini_vol.py:128:0: traceback: ModuleNotFoundError: No module named 'arrow'
ERROR: Found 11 import issue(s) on python 3.8 which need to be resolved:
ERROR: plugins/module_utils/infinibox.py:42:0: traceback: ModuleNotFoundError: No module named 'infinisdk'
ERROR: plugins/modules/infini_cluster.py:65:0: traceback: NameError: name 'api_wrapper' is not defined
ERROR: plugins/modules/infini_export.py:110:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_export_client.py:97:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_fs.py:73:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_host.py:8:0: traceback: ModuleNotFoundError: No module named 'infi'
ERROR: plugins/modules/infini_map.py:90:0: traceback: ModuleNotFoundError: No module named 'infinisdk'
ERROR: plugins/modules/infini_pool.py:108:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_port.py:68:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_user.py:8:0: traceback: ModuleNotFoundError: No module named 'infi'
ERROR: plugins/modules/infini_vol.py:128:0: traceback: ModuleNotFoundError: No module named 'arrow'
ERROR: Found 11 import issue(s) on python 3.9 which need to be resolved:
ERROR: plugins/module_utils/infinibox.py:42:0: traceback: ModuleNotFoundError: No module named 'infinisdk'
ERROR: plugins/modules/infini_cluster.py:65:0: traceback: NameError: name 'api_wrapper' is not defined
ERROR: plugins/modules/infini_export.py:110:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_export_client.py:97:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_fs.py:73:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_host.py:8:0: traceback: ModuleNotFoundError: No module named 'infi'
ERROR: plugins/modules/infini_map.py:90:0: traceback: ModuleNotFoundError: No module named 'infinisdk'
ERROR: plugins/modules/infini_pool.py:108:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_port.py:68:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_user.py:8:0: traceback: ModuleNotFoundError: No module named 'infi'
ERROR: plugins/modules/infini_vol.py:128:0: traceback: ModuleNotFoundError: No module named 'arrow'
ERROR: Found 11 import issue(s) on python 3.10 which need to be resolved:
ERROR: plugins/module_utils/infinibox.py:42:0: traceback: ModuleNotFoundError: No module named 'infinisdk'
ERROR: plugins/modules/infini_cluster.py:65:0: traceback: NameError: name 'api_wrapper' is not defined
ERROR: plugins/modules/infini_export.py:110:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_export_client.py:97:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_fs.py:73:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_host.py:8:0: traceback: ModuleNotFoundError: No module named 'infi'
ERROR: plugins/modules/infini_map.py:90:0: traceback: ModuleNotFoundError: No module named 'infinisdk'
ERROR: plugins/modules/infini_pool.py:108:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_port.py:68:0: traceback: ModuleNotFoundError: No module named 'infinisdk' (at plugins/module_utils/infinibox.py:42:0)
ERROR: plugins/modules/infini_user.py:8:0: traceback: ModuleNotFoundError: No module named 'infi'
ERROR: plugins/modules/infini_vol.py:128:0: traceback: ModuleNotFoundError: No module named 'arrow'
ERROR: Found 1 metaclass-boilerplate issue(s) which need to be resolved:
ERROR: plugins/module_utils/infinibox.py:0:0: missing: __metaclass__ = type
ERROR: Found 10 no-assert issue(s) which need to be resolved:
ERROR: plugins/modules/infini_cluster.py:139:5: raise AssertionError instead of: assert 
ERROR: plugins/modules/infini_export.py:121:5: raise AssertionError instead of: assert 
ERROR: plugins/modules/infini_export.py:138:5: raise AssertionError instead of: assert 
ERROR: plugins/modules/infini_export_client.py:184:5: raise AssertionError instead of: assert 
ERROR: plugins/modules/infini_map.py:271:5: raise AssertionError instead of: assert 
ERROR: plugins/modules/infini_map.py:293:5: raise AssertionError instead of: assert 
ERROR: plugins/modules/infini_user.py:98:13: raise AssertionError instead of: assert 
ERROR: plugins/modules/infini_user.py:150:5: raise AssertionError instead of: assert 
ERROR: plugins/modules/infini_user.py:177:5: raise AssertionError instead of: assert 
ERROR: plugins/modules/infini_vol.py:437:5: raise AssertionError instead of: assert 
ERROR: Found 102 pep8 issue(s) which need to be resolved:
ERROR: plugins/filter/psus_filters.py:8:1: E302: expected 2 blank lines, found 1
ERROR: plugins/filter/psus_filters.py:15:1: E302: expected 2 blank lines, found 1
ERROR: plugins/module_utils/infinibox.py:32:1: E303: too many blank lines (3)
ERROR: plugins/module_utils/infinibox.py:46:46: E226: missing whitespace around arithmetic operator
ERROR: plugins/module_utils/infinibox.py:75:33: E502: the backslash is redundant between brackets
ERROR: plugins/module_utils/infinibox.py:76:65: E502: the backslash is redundant between brackets
ERROR: plugins/module_utils/infinibox.py:77:70: E502: the backslash is redundant between brackets
ERROR: plugins/module_utils/infinibox.py:208:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_cluster.py:190:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_cluster.py:195:16: E225: missing whitespace around operator
ERROR: plugins/modules/infini_cluster.py:197:16: E225: missing whitespace around operator
ERROR: plugins/modules/infini_cluster.py:206:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_cluster.py:209:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_export.py:170:33: E261: at least two spaces before inline comment
ERROR: plugins/modules/infini_export.py:170:34: E262: inline comment should start with '# '
ERROR: plugins/modules/infini_export.py:218:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_export.py:222:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_export_client.py:141:1: E302: expected 2 blank lines, found 1
ERROR: plugins/modules/infini_export_client.py:173:33: E261: at least two spaces before inline comment
ERROR: plugins/modules/infini_export_client.py:173:34: E262: inline comment should start with '# '
ERROR: plugins/modules/infini_export_client.py:175:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_export_client.py:204:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_export_client.py:208:8: E225: missing whitespace around operator
ERROR: plugins/modules/infini_export_client.py:216:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_export_client.py:220:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_fs.py:124:37: E261: at least two spaces before inline comment
ERROR: plugins/modules/infini_fs.py:124:38: E262: inline comment should start with '# '
ERROR: plugins/modules/infini_host.py:65:1: E302: expected 2 blank lines, found 1
ERROR: plugins/modules/infini_host.py:70:1: E302: expected 2 blank lines, found 1
ERROR: plugins/modules/infini_host.py:131:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_host.py:135:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_host.py:143:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_host.py:147:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_map.py:102:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_map.py:103:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_map.py:106:13: E265: block comment should start with '# '
ERROR: plugins/modules/infini_map.py:115:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_map.py:116:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_map.py:119:9: E265: block comment should start with '# '
ERROR: plugins/modules/infini_map.py:121:13: E265: block comment should start with '# '
ERROR: plugins/modules/infini_map.py:209:9: E265: block comment should start with '# '
ERROR: plugins/modules/infini_map.py:243:9: E265: block comment should start with '# '
ERROR: plugins/modules/infini_map.py:472:9: E122: continuation line missing indentation or outdented
ERROR: plugins/modules/infini_map.py:485:9: E122: continuation line missing indentation or outdented
ERROR: plugins/modules/infini_map.py:589:1: E302: expected 2 blank lines, found 1
ERROR: plugins/modules/infini_pool.py:148:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_pool.py:166:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_pool.py:202:31: E261: at least two spaces before inline comment
ERROR: plugins/modules/infini_pool.py:202:32: E262: inline comment should start with '# '
ERROR: plugins/modules/infini_port.py:74:1: E302: expected 2 blank lines, found 1
ERROR: plugins/modules/infini_port.py:141:38: E226: missing whitespace around arithmetic operator
ERROR: plugins/modules/infini_port.py:144:28: E231: missing whitespace after ':'
ERROR: plugins/modules/infini_port.py:156:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_port.py:164:94: E502: the backslash is redundant between brackets
ERROR: plugins/modules/infini_port.py:168:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_port.py:168:5: E303: too many blank lines (2)
ERROR: plugins/modules/infini_port.py:169:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_port.py:172:7: E271: multiple spaces after keyword
ERROR: plugins/modules/infini_port.py:188:23: E221: multiple spaces before operator
ERROR: plugins/modules/infini_port.py:209:21: E265: block comment should start with '# '
ERROR: plugins/modules/infini_port.py:223:42: E226: missing whitespace around arithmetic operator
ERROR: plugins/modules/infini_port.py:239:21: E265: block comment should start with '# '
ERROR: plugins/modules/infini_user.py:91:35: E128: continuation line under-indented for visual indent
ERROR: plugins/modules/infini_user.py:92:35: E128: continuation line under-indented for visual indent
ERROR: plugins/modules/infini_user.py:93:35: E128: continuation line under-indented for visual indent
ERROR: plugins/modules/infini_user.py:94:35: E124: closing bracket does not match visual indentation
ERROR: plugins/modules/infini_user.py:114:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_user.py:118:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_user.py:119:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_user.py:120:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_user.py:122:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_user.py:125:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_user.py:127:32: E261: at least two spaces before inline comment
ERROR: plugins/modules/infini_user.py:127:33: E262: inline comment should start with '# '
ERROR: plugins/modules/infini_user.py:129:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_user.py:130:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_user.py:149:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_user.py:154:34: E241: multiple spaces after ','
ERROR: plugins/modules/infini_user.py:176:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_user.py:196:5: E265: block comment should start with '# '
ERROR: plugins/modules/infini_user.py:234:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_user.py:238:16: E225: missing whitespace around operator
ERROR: plugins/modules/infini_user.py:240:16: E225: missing whitespace around operator
ERROR: plugins/modules/infini_user.py:249:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_user.py:252:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_user.py:264:12: E225: missing whitespace around operator
ERROR: plugins/modules/infini_user.py:287:10: E221: multiple spaces before operator
ERROR: plugins/modules/infini_user.py:303:9: E271: multiple spaces after keyword
ERROR: plugins/modules/infini_vol.py:288:18: E222: multiple spaces after operator
ERROR: plugins/modules/infini_vol.py:297:34: E226: missing whitespace around arithmetic operator
ERROR: plugins/modules/infini_vol.py:297:38: E226: missing whitespace around arithmetic operator
ERROR: plugins/modules/infini_vol.py:338:33: E261: at least two spaces before inline comment
ERROR: plugins/modules/infini_vol.py:338:34: E262: inline comment should start with '# '
ERROR: plugins/modules/infini_vol.py:341:20: E225: missing whitespace around operator
ERROR: plugins/modules/infini_vol.py:456:10: E221: multiple spaces before operator
ERROR: plugins/modules/infini_vol.py:457:9: E221: multiple spaces before operator
ERROR: plugins/modules/infini_vol.py:458:9: E221: multiple spaces before operator
ERROR: plugins/modules/infini_vol.py:459:16: E221: multiple spaces before operator
ERROR: plugins/modules/infini_vol.py:460:23: E221: multiple spaces before operator
ERROR: plugins/modules/infini_vol.py:466:26: E222: multiple spaces after operator
ERROR: plugins/modules/infini_vol.py:474:22: E222: multiple spaces after operator
ERROR: plugins/modules/infini_vol.py:479:26: E222: multiple spaces after operator
ERROR: Command "/root/.ansible/test/venv/sanity.validate-modules/3.10/487215fd/bin/python /root/ansible/test/lib/ansible_test/_util/controller/sanity/validate-modules/validate.py --format json --arg-spec --collection ansible_collections/infinidat/infinibox --collection-version 1.3.3 plugins/modules/infini_cluster.py plugins/modules/infini_export.py plugins/modules/infini_export_client.py plugins/modules/infini_fs.py plugins/modules/infini_host.py plugins/modules/infini_map.py plugins/modules/infini_pool.py plugins/modules/infini_port.py plugins/modules/infini_user.py plugins/modules/infini_vol.py" returned exit status 1.
>>> Standard Error
Traceback (most recent call last):
  File "/root/ansible/test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/utils.py", line 153, in parse_yaml
    data = yaml_load(value, Loader=loader)
  File "/root/.ansible/test/venv/sanity.validate-modules/3.10/487215fd/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/root/.ansible/test/venv/sanity.validate-modules/3.10/487215fd/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 687, in yaml._yaml.CParser._compose_document
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 845, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 845, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 845, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 729, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 808, in yaml._yaml.CParser._compose_sequence_node
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a block collection
  in "<unicode string>", line 54, column 7
did not find expected '-' indicator
  in "<unicode string>", line 55, column 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ansible/test/lib/ansible_test/_util/controller/sanity/validate-modules/validate.py", line 6, in <module>
    main()
  File "/root/ansible/test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py", line 2475, in main
    run()
  File "/root/ansible/test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py", line 2364, in run
    mv1.validate()
  File "/root/ansible/test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py", line 2157, in validate
    doc_info, docs = self._validate_docs()
  File "/root/ansible/test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py", line 940, in _validate_docs
    doc, errors, traces = parse_yaml(
  File "/root/ansible/test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/utils.py", line 157, in parse_yaml
    e.problem_mark.line += lineno - 1
AttributeError: attribute 'line' of 'yaml._yaml.Mark' objects is not writable[0m
ERROR: Command "podman exec ansible-test-controller-e1cD83dz /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible_collections/infinidat/infinibox LC_ALL=en_US.UTF-8 /usr/bin/python3.10 /root/ansible/bin/ansible-test sanity --containers '{}' --skip-test pylint --metadata tests/output/.tmp/metadata-2yynegnt.json --truncate 0 --color no --host-path tests/output/.tmp/host-k6puj547" returned exit status 1.
```

**Comment by sqqqrly** [comment]
This is fixed in v1.3.7.
